language: en-US
early_access: false
reviews:
  profile: assertive
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false
  tools:
    eslint:
      enabled: true
    biome:
      enabled: true
chat:
  auto_reply: true
tone_instructions: |
  You are reviewing Vue.js 3 public portfolio website code.

  Focus on:
  - Vue 3 Composition API best practices (proper use of ref, computed, watch)
  - Component design and reusability
  - Naive UI component usage
  - Performance (bundle size, lazy loading, image optimization, code splitting)
  - SEO (meta tags, semantic HTML, SSR considerations, structured data)
  - Accessibility (WCAG 2.1 AA compliance, ARIA, keyboard navigation, color contrast)
  - Responsive design (mobile-first, touch targets, viewport handling)
  - Core Web Vitals (LCP, FID, CLS optimization)
  - API integration and loading states
  - Error boundaries and graceful degradation

  This is a PUBLIC-FACING website - prioritize:
  1. Performance (fast load times, optimized images)
  2. Accessibility (all users should have great experience)
  3. SEO (proper meta tags, semantic HTML)
  4. Mobile experience (responsive, touch-friendly)

  Suggest specific performance optimizations and accessibility improvements.
